---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: beta-backend

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

shared:
- params: &om-creds
    OM_USERNAME: ((om.username))
    OM_PASSWORD: ((om.password))

resources:
- name: cf-infra-tracker
  type: tracker
  source:
    token: ((cf_infra_tracker_token))
    project_id: ((cf_infrastructure_tracker_id))
    tracker_url: https://www.pivotaltracker.com

- name: after-midnight
  type: time
  source:
    start: 12:00 AM -0700
    stop: 2:00 AM -0700

- name: terraforming
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/terraforming-gcp.git
    private_key: ((cf_infra_bot_github_user.private_key))

- name: terraforming-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: terraforming-gcp
    access_token: ((cf_infra_bot_user_github_access_token))
    drafts: true

- name: version
  type: semver
  source:
    driver: s3
    bucket: terraforming
    key: terraforming-gcp/version
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))

- name: env-state-gcp
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      bucket: infra-tf-states
      prefix: gcp
      region: us-east1
      credentials: ((cf_infra_gcp_service_account_key))
    vars:
      project: ((cf_infra_gcp_project_id))
      region: us-east1
      zones: ["us-east1-b", "us-east1-c",  "us-east1-d"]
      dns_suffix: gcp.infrastructure.cf-app.com
      top_level_zone_name: ((terraforming-gcp-root-zone-name))
      isolation_segment: true
      service_account_key: ((cf_infra_gcp_service_account_key))
      ssl_cert: ((terraforming-gcp.certificate))
      ssl_private_key: ((terraforming-gcp.private_key))
      iso_seg_ssl_cert: ((terraforming-gcp.certificate))
      iso_seg_ssl_private_key: ((terraforming-gcp.private_key))

- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: pcf-releng-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-releng-ci.git
    private_key: ((cf_infra_bot_github_user.private_key))
    ignore_paths:
    - pipelines
    - ci_screen

- name: srt
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: elastic-runtime
    product_version: ^\d+\.\d+\.\d+
    sort_by: semver

- name: pks
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: pivotal-container-service
    product_version: ^\d+\.\d+\.\d+
    sort_by: semver

- name: opsman-image
  type: pivnet
  source:
    product_slug: ops-manager
    api_token: ((pivnet_token))
    product_version: ^\d+\.\d+\.\d+
    sort_by: semver

- name: tile-ci
  type: git
  source:
    branch: master
    paths:
    - ci/*
    - config/*
    private_key: ((control-plane-tile-repo.private_key))
    uri: git@github.com:pivotal/control-plane-tile.git

jobs:
- name: deploy-pas
  serial: true
  public: false
  plan:
  - in_parallel:
    - get: after-midnight
      trigger: true
    - get: terraforming
      trigger: true
    - get: ci
      resource: infrastructure-ci
    - get: pcf-releng-ci
    - get: srt
      trigger: true
      params:
        globs:
        - srt-*.pivotal
    - get: opsman-image
      trigger: true
      params:
        globs:
        - '*gcp*.yml'
    - get: cp-ci
      resource: tile-ci
  - do:
    - task: opsman-url
      file: ci/scripts/terraforming/latest-opsman/task.yml
      params:
        IAAS: gcp
        KEY: us
    - put: env-state-gcp
      params:
        env_name: tf-ci
        terraform_source: terraforming/terraforming-pas
        delete_on_failure: true
        var_files: [tfvars/terraform.yml]
        override_files:
        - terraforming/ci/dns-override/gcp_dns_root_zone_override.tf
    - task: configure-authentication
      file: cp-ci/ci/tasks/configure-authentication/task.yml
      params:
        OM_PASSWORD: ((om.password))
        OM_USERNAME: ((om.username))
      input_mapping:
        env-state: env-state-gcp
    - task: configure-director
      file: ci/scripts/terraforming/configure-director/task.yml
      params:
        <<: *om-creds
        CA_CERT: ((terraforming-ca.ca))
        TEMPLATE_PATH: director-config-template/ci/assets/template/director-config.yml
      input_mapping:
        env-state: env-state-gcp
        director-config-template: terraforming
    - task: download-stemcell
      file: pcf-releng-ci/tasks/configuration/download-pivnet-stemcell/task.yml
      input_mapping:
        ert-product: srt
      params:
        IAAS_TYPE: gcp
        PIVNET_TOKEN: ((pivnet_token))
    - task: upload-configure-stage-pas
      file: ci/scripts/terraforming/upload-configure-stage/task.yml
      params:
        <<: *om-creds
        PRODUCT_NAME: cf
        PRODUCT_CONFIG_TEMPLATE: ci/assets/template/srt-config.yml
      input_mapping:
        env-state: env-state-gcp
        product: srt
        product-config-repo: terraforming
    - task: apply-changes
      file: ci/scripts/terraforming/apply-changes/task.yml
      params:
        <<: *om-creds
      input_mapping:
        env-state: env-state-gcp
    ensure:
      do:
      - task: delete-installation
        file: pcf-releng-ci/tasks/environment/delete-installation/task.yml
        params:
          OPSMAN_USERNAME: ((om.username))
          OPSMAN_PASSWORD: ((om.password))
          OPSMAN_URL_SUFFIX: gcp.infrastructure.cf-app.com
        input_mapping:
          environment: env-state-gcp
      - put: env-state-gcp
        params:
          terraform_source: terraforming/terraforming-pas
          delete_on_failure: true
          env_name_file: env-state-gcp/name
          action: destroy
          var_files: [tfvars/terraform.yml]
          override_files:
          - terraforming/ci/dns-override/gcp_dns_root_zone_override.tf
        get_params:
          action: destroy

- name: deploy-pks
  serial: true
  public: false
  plan:
  - in_parallel:
    - get: after-midnight
      trigger: true
    - get: terraforming
      trigger: true
    - get: ci
      resource: infrastructure-ci
    - get: pcf-releng-ci
    - get: pks
      trigger: true
    - get: opsman-image
      trigger: true
      params:
        globs:
        - '*gcp*.yml'
    - get: cp-ci
      resource: tile-ci
  - do:
    - task: opsman-url
      file: ci/scripts/terraforming/latest-opsman/task.yml
      params:
        IAAS: gcp
        KEY: us
    - put: env-state-gcp
      params:
        env_name: tf-pks-ci
        terraform_source: terraforming/terraforming-pks
        delete_on_failure: true
        var_files: [tfvars/terraform.yml]
        override_files:
        - terraforming/ci/dns-override/gcp_dns_root_zone_override.tf
    - task: configure-authentication
      file: cp-ci/ci/tasks/configure-authentication/task.yml
      params:
        OM_PASSWORD: ((om.password))
        OM_USERNAME: ((om.username))
      input_mapping:
        env-state: env-state-gcp
    - task: configure-director
      file: ci/scripts/terraforming/configure-director/task.yml
      params:
        <<: *om-creds
        TEMPLATE_PATH: director-config-template/ci/assets/template/director-config.yml
        CA_CERT: ((terraforming-ca.ca))
      input_mapping:
        env-state: env-state-gcp
        director-config-template: terraforming
    - task: download-stemcell
      file: pcf-releng-ci/tasks/configuration/download-pivnet-stemcell/task.yml
      input_mapping:
        ert-product: pks
      params:
        IAAS_TYPE: gcp
        PIVNET_TOKEN: ((pivnet_token))
    - task: upload-configure-stage-pks
      file: ci/scripts/terraforming/upload-configure-stage/task.yml
      params:
        <<: *om-creds
        PRODUCT_NAME: pivotal-container-service
        PRODUCT_CONFIG_TEMPLATE: ci/assets/template/pks-config.yml
      input_mapping:
        env-state: env-state-gcp
        product: pks
        product-config-repo: terraforming
    - task: apply-changes
      file: ci/scripts/terraforming/apply-changes/task.yml
      params:
        <<: *om-creds
      input_mapping:
        env-state: env-state-gcp
    ensure:
      do:
      - task: delete-installation
        file: pcf-releng-ci/tasks/environment/delete-installation/task.yml
        params:
          OPSMAN_USERNAME: ((om.username))
          OPSMAN_PASSWORD: ((om.password))
          OPSMAN_URL_SUFFIX: gcp.infrastructure.cf-app.com
        input_mapping:
          environment: env-state-gcp
      - put: env-state-gcp
        params:
          terraform_source: terraforming/terraforming-pks
          env_name_file: env-state-gcp/name
          delete_on_failure: true
          action: destroy
          var_files: [tfvars/terraform.yml]
          override_files:
          - terraforming/ci/dns-override/gcp_dns_root_zone_override.tf
        get_params:
          action: destroy

- name: publish
  serial: true
  plan:
  - in_parallel:
    - get: terraforming
      passed:
      - deploy-pas
      - deploy-pks
      trigger: true
    - get: version
      params:
        bump: minor
    - get: ci
      resource: infrastructure-ci
  - task: release
    file: ci/scripts/terraforming/release/task.yml
    params:
      IAAS: gcp
  - put: terraforming-release
    params:
      name: release/version
      tag: release/version
      commitish: release/commitish
      globs:
      - release/terraforming-gcp-*.tar.gz
  - put: version
    params:
      bump: minor
      file: version/version

- name: deliver-stories
  plan:
  - get: terraforming
    trigger: true
    passed:
    - deploy-pas
    - deploy-pks
  - put: cf-infra-tracker
    params:
      repos:
      - terraforming
