---
product-name: control-plane
network-properties:
  network:
    name: {{.control_plane_subnet_name}}
  other_availability_zones:
    {{range .azs}}
    - name: {{.}}
    {{end}}
  singleton_availability_zone:
    name: {{index .azs 0}}
product-properties:
  .properties.root_domain:
    value: {{.control_plane_root_domain}}
  .properties.tls:
    value:
      cert_pem: {{printf "%q" .control_plane_cert}}
      private_key_pem: {{printf "%q" .control_plane_key}}
  .properties.uaa_ca_cert:
    value: {{printf "%q" .control_plane_lb_ca_cert}}
resource-config:
  web:
    elb_names:
    - tcp:{{.control_plane_lb_name}}
    internet_connected: false
  uaa:
    elb_names:
    - http:{{.control_plane_uaa_lb_name}}
    internet_connected: false
  credhub:
    elb_names:
    - http:{{.control_plane_credhub_lb_name}}
    internet_connected: false
  db:
    internet_connected: false
  worker:
    internet_connected: true
